//> using scala 3.3.3
//> using repository jitpack
//> using repository https://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/
//> using dep org.typelevel::cats-core:2.12.0
//> using dep org.typelevel::cats-effect:3.5.4
//> using dep co.fs2::fs2-core:3.10.2
//> using dep com.github.latis-data.latis3::latis3-core:9e5b31b
//> using dep com.github.latis-data.latis3::latis3-netcdf:9e5b31b
//> using dep com.github.latis-data.latis3::latis3-server:9e5b31b
//> using dep com.github.lasp:hapi-server:5cab19f
//> using dep ch.qos.logback:logback-classic:1.5.6
